spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/moayoeats
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER_NAME}:${MONGO_PASSWORD}@${CLUSTER_URL}/moayoeats?retryWrites=true&w=majority
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      show_sql: true
      generate-ddl: true

  thymeleaf:
    cache: false
    suffix: .html
#    prefix: src/main/resources/templates/

jwt:
  secret:
    key: ${JWT_SECRET_KEY}